#region Copyright Syncfusion® Inc. 2001-2026.
// Copyright Syncfusion® Inc. 2001-2026. All rights reserved.
// Use of this code is subject to the terms of our license.
// A copy of the current license can be obtained at any time by e-mailing
// licensing@syncfusion.com. Any infringement will be prosecuted under
// applicable laws. 
#endregion
using System.Collections.Generic;
namespace BlazorDemos.Pages.PivotView.PivotTable
{
    public class SalesData
    {
        public int Year { get; set; }
        public string Region { get; set; } = string.Empty;
        public string Country { get; set; } = string.Empty;
        public string Product { get; set; } = string.Empty;
        public int Sold { get; set; }
        public int Amount { get; set; }
    }

    public static class SalesDataStore
    {
        public static List<SalesData> Records { get; } = new List<SalesData>
        {
            new SalesData { Year = 2019, Region = "North America", Country = "USA", Product = "Laptop", Sold = 326, Amount = 376530 },
            new SalesData { Year = 2019, Region = "North America", Country = "USA", Product = "Smartphone", Sold = -425, Amount = -390575 },
            new SalesData { Year = 2019, Region = "North America", Country = "USA", Product = "Tablet", Sold = 117, Amount = 62478 },
            new SalesData { Year = 2019, Region = "North America", Country = "USA", Product = "Monitor", Sold = 490, Amount = 271950 },
            new SalesData { Year = 2019, Region = "North America", Country = "USA", Product = "Printer", Sold = 462, Amount = 200508 },
            new SalesData { Year = 2019, Region = "North America", Country = "Canada", Product = "Laptop", Sold = 264, Amount = 231528 },
            new SalesData { Year = 2019, Region = "North America", Country = "Canada", Product = "Smartphone", Sold = 362, Amount = 402182 },
            new SalesData { Year = 2019, Region = "North America", Country = "Canada", Product = "Tablet", Sold = 472, Amount = 339840 },
            new SalesData { Year = 2019, Region = "North America", Country = "Canada", Product = "Monitor", Sold = -343, Amount = -279202 },
            new SalesData { Year = 2019, Region = "North America", Country = "Canada", Product = "Printer", Sold = 368, Amount = 284464 },
            new SalesData { Year = 2019, Region = "North America", Country = "Mexico", Product = "Laptop", Sold = 307, Amount = 230864 },
            new SalesData { Year = 2019, Region = "North America", Country = "Mexico", Product = "Smartphone", Sold = -273, Amount = -280644 },
            new SalesData { Year = 2019, Region = "North America", Country = "Mexico", Product = "Tablet", Sold = 468, Amount = 195156 },
            new SalesData { Year = 2019, Region = "North America", Country = "Mexico", Product = "Monitor", Sold = 299, Amount = 61893 },
            new SalesData { Year = 2019, Region = "North America", Country = "Mexico", Product = "Printer", Sold = 106, Amount = 65720 },
            new SalesData { Year = 2019, Region = "South America", Country = "Brazil", Product = "Laptop", Sold = 299, Amount = 289731 },
            new SalesData { Year = 2019, Region = "South America", Country = "Brazil", Product = "Smartphone", Sold = 178, Amount = 48950 },
            new SalesData { Year = 2019, Region = "South America", Country = "Brazil", Product = "Tablet", Sold = -460, Amount = -414920 },
            new SalesData { Year = 2019, Region = "South America", Country = "Brazil", Product = "Monitor", Sold = 329, Amount = 341831 },
            new SalesData { Year = 2019, Region = "South America", Country = "Brazil", Product = "Printer", Sold = 205, Amount = 55965 },
            new SalesData { Year = 2019, Region = "South America", Country = "Argentina", Product = "Laptop", Sold = 489, Amount = 220539 },
            new SalesData { Year = 2019, Region = "South America", Country = "Argentina", Product = "Smartphone", Sold = 338, Amount = 217334 },
            new SalesData { Year = 2019, Region = "South America", Country = "Argentina", Product = "Tablet", Sold = 422, Amount = 384442 },
            new SalesData { Year = 2019, Region = "South America", Country = "Argentina", Product = "Monitor", Sold = 334, Amount = 98530 },
            new SalesData { Year = 2019, Region = "South America", Country = "Argentina", Product = "Printer", Sold = 236, Amount = 148208 },
            new SalesData { Year = 2019, Region = "South America", Country = "Chile", Product = "Laptop", Sold = 475, Amount = 462650 },
            new SalesData { Year = 2019, Region = "South America", Country = "Chile", Product = "Smartphone", Sold = 446, Amount = 516914 },
            new SalesData { Year = 2019, Region = "South America", Country = "Chile", Product = "Tablet", Sold = 383, Amount = 279590 },
            new SalesData { Year = 2019, Region = "South America", Country = "Chile", Product = "Monitor", Sold = 343, Amount = 134113 },
            new SalesData { Year = 2019, Region = "South America", Country = "Chile", Product = "Printer", Sold = 110, Amount = 21780 },
            new SalesData { Year = 2019, Region = "Europe", Country = "Germany", Product = "Laptop", Sold = -133, Amount = -153216 },
            new SalesData { Year = 2019, Region = "Europe", Country = "Germany", Product = "Smartphone", Sold = 458, Amount = 248236 },
            new SalesData { Year = 2019, Region = "Europe", Country = "Germany", Product = "Tablet", Sold = 292, Amount = 134612 },
            new SalesData { Year = 2019, Region = "Europe", Country = "Germany", Product = "Monitor", Sold = 399, Amount = 119700 },
            new SalesData { Year = 2019, Region = "Europe", Country = "Germany", Product = "Printer", Sold = 377, Amount = 84825 },
            new SalesData { Year = 2019, Region = "Europe", Country = "France", Product = "Laptop", Sold = 107, Amount = 122087 },
            new SalesData { Year = 2019, Region = "Europe", Country = "France", Product = "Smartphone", Sold = 323, Amount = 229330 },
            new SalesData { Year = 2019, Region = "Europe", Country = "France", Product = "Tablet", Sold = 377, Amount = 398489 },
            new SalesData { Year = 2019, Region = "Europe", Country = "France", Product = "Monitor", Sold = 172, Amount = 75508 },
            new SalesData { Year = 2019, Region = "Europe", Country = "France", Product = "Printer", Sold = 423, Amount = 347706 },
            new SalesData { Year = 2019, Region = "Europe", Country = "UK", Product = "Laptop", Sold = 362, Amount = 144438 },
            new SalesData { Year = 2019, Region = "Europe", Country = "UK", Product = "Smartphone", Sold = 221, Amount = 57018 },
            new SalesData { Year = 2019, Region = "Europe", Country = "UK", Product = "Tablet", Sold = 172, Amount = 26144 },
            new SalesData { Year = 2019, Region = "Europe", Country = "UK", Product = "Monitor", Sold = -100, Amount = -38000 },
            new SalesData { Year = 2019, Region = "Europe", Country = "UK", Product = "Printer", Sold = 128, Amount = 53760 },
            new SalesData { Year = 2019, Region = "Asia", Country = "China", Product = "Laptop", Sold = 215, Amount = 54610 },
            new SalesData { Year = 2019, Region = "Asia", Country = "China", Product = "Smartphone", Sold = -398, Amount = -383274 },
            new SalesData { Year = 2019, Region = "Asia", Country = "China", Product = "Tablet", Sold = 472, Amount = 307272 },
            new SalesData { Year = 2019, Region = "Asia", Country = "China", Product = "Monitor", Sold = 135, Amount = 145530 },
            new SalesData { Year = 2019, Region = "Asia", Country = "China", Product = "Printer", Sold = 159, Amount = 169335 },
            new SalesData { Year = 2019, Region = "Asia", Country = "India", Product = "Laptop", Sold = 383, Amount = 96899 },
            new SalesData { Year = 2019, Region = "Asia", Country = "India", Product = "Smartphone", Sold = 222, Amount = 241536 },
            new SalesData { Year = 2019, Region = "Asia", Country = "India", Product = "Tablet", Sold = 200, Amount = 224800 },
            new SalesData { Year = 2019, Region = "Asia", Country = "India", Product = "Monitor", Sold = -420, Amount = -362460 },
            new SalesData { Year = 2019, Region = "Asia", Country = "India", Product = "Printer", Sold = 106, Amount = 82574 },
            new SalesData { Year = 2019, Region = "Asia", Country = "Japan", Product = "Laptop", Sold = 228, Amount = 51756 },
            new SalesData { Year = 2019, Region = "Asia", Country = "Japan", Product = "Smartphone", Sold = 490, Amount = 549290 },
            new SalesData { Year = 2019, Region = "Asia", Country = "Japan", Product = "Tablet", Sold = 338, Amount = 401206 },
            new SalesData { Year = 2019, Region = "Asia", Country = "Japan", Product = "Monitor", Sold = 299, Amount = 216177 },
            new SalesData { Year = 2019, Region = "Asia", Country = "Japan", Product = "Printer", Sold = 189, Amount = 61992 },
            new SalesData { Year = 2019, Region = "Africa", Country = "Nigeria", Product = "Laptop", Sold = -112, Amount = -68656 },
            new SalesData { Year = 2019, Region = "Africa", Country = "Nigeria", Product = "Smartphone", Sold = -197, Amount = -42158 },
            new SalesData { Year = 2019, Region = "Africa", Country = "Nigeria", Product = "Tablet", Sold = 122, Amount = 20618 },
            new SalesData { Year = 2019, Region = "Africa", Country = "Nigeria", Product = "Monitor", Sold = 240, Amount = 147120 },
            new SalesData { Year = 2019, Region = "Africa", Country = "Nigeria", Product = "Printer", Sold = 342, Amount = 153216 },
            new SalesData { Year = 2019, Region = "Africa", Country = "Egypt", Product = "Laptop", Sold = 179, Amount = 50299 },
            new SalesData { Year = 2019, Region = "Africa", Country = "Egypt", Product = "Smartphone", Sold = 287, Amount = 97293 },
            new SalesData { Year = 2019, Region = "Africa", Country = "Egypt", Product = "Tablet", Sold = -484, Amount = -519816 },
            new SalesData { Year = 2019, Region = "Africa", Country = "Egypt", Product = "Monitor", Sold = 448, Amount = 479360 },
            new SalesData { Year = 2019, Region = "Africa", Country = "Egypt", Product = "Printer", Sold = 282, Amount = 102648 },
            new SalesData { Year = 2019, Region = "Africa", Country = "South Africa", Product = "Laptop", Sold = 205, Amount = 36695 },
            new SalesData { Year = 2019, Region = "Africa", Country = "South Africa", Product = "Smartphone", Sold = 321, Amount = 117486 },
            new SalesData { Year = 2019, Region = "Africa", Country = "South Africa", Product = "Tablet", Sold = 293, Amount = 108703 },
            new SalesData { Year = 2019, Region = "Africa", Country = "South Africa", Product = "Monitor", Sold = -193, Amount = -129117 },
            new SalesData { Year = 2019, Region = "Africa", Country = "South Africa", Product = "Printer", Sold = 356, Amount = 323604 },
            new SalesData { Year = 2019, Region = "Australia", Country = "Australia", Product = "Laptop", Sold = 142, Amount = 53960 },
            new SalesData { Year = 2019, Region = "Australia", Country = "Australia", Product = "Smartphone", Sold = -416, Amount = -72384 },
            new SalesData { Year = 2019, Region = "Australia", Country = "Australia", Product = "Tablet", Sold = 402, Amount = 412854 },
            new SalesData { Year = 2019, Region = "Australia", Country = "Australia", Product = "Monitor", Sold = 273, Amount = 60060 },
            new SalesData { Year = 2019, Region = "Australia", Country = "Australia", Product = "Printer", Sold = 269, Amount = 138804 },
            new SalesData { Year = 2019, Region = "Australia", Country = "New Zealand", Product = "Laptop", Sold = 235, Amount = 38305 },
            new SalesData { Year = 2019, Region = "Australia", Country = "New Zealand", Product = "Smartphone", Sold = 500, Amount = 505500 },
            new SalesData { Year = 2019, Region = "Australia", Country = "New Zealand", Product = "Tablet", Sold = 379, Amount = 291451 },
            new SalesData { Year = 2019, Region = "Australia", Country = "New Zealand", Product = "Monitor", Sold = 343, Amount = 361865 },
            new SalesData { Year = 2019, Region = "Australia", Country = "New Zealand", Product = "Printer", Sold = 215, Amount = 256710 },
            new SalesData { Year = 2020, Region = "North America", Country = "USA", Product = "Laptop", Sold = 441, Amount = 78057 },
            new SalesData { Year = 2020, Region = "North America", Country = "USA", Product = "Smartphone", Sold = 157, Amount = 42861 },
            new SalesData { Year = 2020, Region = "North America", Country = "USA", Product = "Tablet", Sold = -498, Amount = -419814 },
            new SalesData { Year = 2020, Region = "North America", Country = "USA", Product = "Monitor", Sold = -227, Amount = -163213 },
            new SalesData { Year = 2020, Region = "North America", Country = "USA", Product = "Printer", Sold = -286, Amount = -338910 },
            new SalesData { Year = 2020, Region = "North America", Country = "Canada", Product = "Laptop", Sold = 155, Amount = 153295 },
            new SalesData { Year = 2020, Region = "North America", Country = "Canada", Product = "Smartphone", Sold = 437, Amount = 443555 },
            new SalesData { Year = 2020, Region = "North America", Country = "Canada", Product = "Tablet", Sold = -337, Amount = -128734 },
            new SalesData { Year = 2020, Region = "North America", Country = "Canada", Product = "Monitor", Sold = 299, Amount = 104052 },
            new SalesData { Year = 2020, Region = "North America", Country = "Canada", Product = "Printer", Sold = -169, Amount = -67600 },
            new SalesData { Year = 2020, Region = "North America", Country = "Mexico", Product = "Laptop", Sold = 248, Amount = 146072 },
            new SalesData { Year = 2020, Region = "North America", Country = "Mexico", Product = "Smartphone", Sold = 410, Amount = 293150 },
            new SalesData { Year = 2020, Region = "North America", Country = "Mexico", Product = "Tablet", Sold = -393, Amount = -225189 },
            new SalesData { Year = 2020, Region = "North America", Country = "Mexico", Product = "Monitor", Sold = 157, Amount = 123873 },
            new SalesData { Year = 2020, Region = "North America", Country = "Mexico", Product = "Printer", Sold = 145, Amount = 63365 },
            new SalesData { Year = 2020, Region = "South America", Country = "Brazil", Product = "Laptop", Sold = -242, Amount = -249986 },
            new SalesData { Year = 2020, Region = "South America", Country = "Brazil", Product = "Smartphone", Sold = 259, Amount = 164724 },
            new SalesData { Year = 2020, Region = "South America", Country = "Brazil", Product = "Tablet", Sold = -228, Amount = -46740 },
            new SalesData { Year = 2020, Region = "South America", Country = "Brazil", Product = "Monitor", Sold = 477, Amount = 235161 },
            new SalesData { Year = 2020, Region = "South America", Country = "Brazil", Product = "Printer", Sold = -263, Amount = -141494 },
            new SalesData { Year = 2020, Region = "South America", Country = "Argentina", Product = "Laptop", Sold = 117, Amount = 106002 },
            new SalesData { Year = 2020, Region = "South America", Country = "Argentina", Product = "Smartphone", Sold = 113, Amount = 59325 },
            new SalesData { Year = 2020, Region = "South America", Country = "Argentina", Product = "Tablet", Sold = 489, Amount = 182397 },
            new SalesData { Year = 2020, Region = "South America", Country = "Argentina", Product = "Monitor", Sold = 401, Amount = 447516 },
            new SalesData { Year = 2020, Region = "South America", Country = "Argentina", Product = "Printer", Sold = -237, Amount = -116841 },
            new SalesData { Year = 2020, Region = "South America", Country = "Chile", Product = "Laptop", Sold = 384, Amount = 430848 },
            new SalesData { Year = 2020, Region = "South America", Country = "Chile", Product = "Smartphone", Sold = -345, Amount = -324300 },
            new SalesData { Year = 2020, Region = "South America", Country = "Chile", Product = "Tablet", Sold = 331, Amount = 285653 },
            new SalesData { Year = 2020, Region = "South America", Country = "Chile", Product = "Monitor", Sold = 194, Amount = 189732 },
            new SalesData { Year = 2020, Region = "South America", Country = "Chile", Product = "Printer", Sold = 434, Amount = 480872 },
            new SalesData { Year = 2020, Region = "Europe", Country = "Germany", Product = "Laptop", Sold = 141, Amount = 134373 },
            new SalesData { Year = 2020, Region = "Europe", Country = "Germany", Product = "Smartphone", Sold = 415, Amount = 138610 },
            new SalesData { Year = 2020, Region = "Europe", Country = "Germany", Product = "Tablet", Sold = 182, Amount = 99372 },
            new SalesData { Year = 2020, Region = "Europe", Country = "Germany", Product = "Monitor", Sold = 476, Amount = 182308 },
            new SalesData { Year = 2020, Region = "Europe", Country = "Germany", Product = "Printer", Sold = 255, Amount = 254745 },
            new SalesData { Year = 2020, Region = "Europe", Country = "France", Product = "Laptop", Sold = 169, Amount = 56784 },
            new SalesData { Year = 2020, Region = "Europe", Country = "France", Product = "Smartphone", Sold = 296, Amount = 44696 },
            new SalesData { Year = 2020, Region = "Europe", Country = "France", Product = "Tablet", Sold = 169, Amount = 89908 },
            new SalesData { Year = 2020, Region = "Europe", Country = "France", Product = "Monitor", Sold = 150, Amount = 144750 },
            new SalesData { Year = 2020, Region = "Europe", Country = "France", Product = "Printer", Sold = 460, Amount = 197800 },
            new SalesData { Year = 2020, Region = "Europe", Country = "UK", Product = "Laptop", Sold = -372, Amount = -441564 },
            new SalesData { Year = 2020, Region = "Europe", Country = "UK", Product = "Smartphone", Sold = 439, Amount = 91312 },
            new SalesData { Year = 2020, Region = "Europe", Country = "UK", Product = "Tablet", Sold = 237, Amount = 242925 },
            new SalesData { Year = 2020, Region = "Europe", Country = "UK", Product = "Monitor", Sold = 102, Amount = 106182 },
            new SalesData { Year = 2020, Region = "Europe", Country = "UK", Product = "Printer", Sold = 357, Amount = 195636 },
            new SalesData { Year = 2020, Region = "Asia", Country = "China", Product = "Laptop", Sold = -293, Amount = -101378 },
            new SalesData { Year = 2020, Region = "Asia", Country = "China", Product = "Smartphone", Sold = 154, Amount = 170632 },
            new SalesData { Year = 2020, Region = "Asia", Country = "China", Product = "Tablet", Sold = 114, Amount = 124146 },
            new SalesData { Year = 2020, Region = "Asia", Country = "China", Product = "Monitor", Sold = 470, Amount = 535330 },
            new SalesData { Year = 2020, Region = "Asia", Country = "China", Product = "Printer", Sold = 294, Amount = 72912 },
            new SalesData { Year = 2020, Region = "Asia", Country = "India", Product = "Laptop", Sold = 103, Amount = 26883 },
            new SalesData { Year = 2020, Region = "Asia", Country = "India", Product = "Smartphone", Sold = 494, Amount = 568100 },
            new SalesData { Year = 2020, Region = "Asia", Country = "India", Product = "Tablet", Sold = 305, Amount = 138775 },
            new SalesData { Year = 2020, Region = "Asia", Country = "India", Product = "Monitor", Sold = 386, Amount = 295676 },
            new SalesData { Year = 2020, Region = "Asia", Country = "India", Product = "Printer", Sold = 271, Amount = 251217 },
            new SalesData { Year = 2020, Region = "Asia", Country = "Japan", Product = "Laptop", Sold = 318, Amount = 244224 },
            new SalesData { Year = 2020, Region = "Asia", Country = "Japan", Product = "Smartphone", Sold = 442, Amount = 419458 },
            new SalesData { Year = 2020, Region = "Asia", Country = "Japan", Product = "Tablet", Sold = 175, Amount = 124950 },
            new SalesData { Year = 2020, Region = "Asia", Country = "Japan", Product = "Monitor", Sold = -493, Amount = -190791 },
            new SalesData { Year = 2020, Region = "Asia", Country = "Japan", Product = "Printer", Sold = 182, Amount = 174902 },
            new SalesData { Year = 2020, Region = "Africa", Country = "Nigeria", Product = "Laptop", Sold = 182, Amount = 50596 },
            new SalesData { Year = 2020, Region = "Africa", Country = "Nigeria", Product = "Smartphone", Sold = 160, Amount = 121440 },
            new SalesData { Year = 2020, Region = "Africa", Country = "Nigeria", Product = "Tablet", Sold = 333, Amount = 234765 },
            new SalesData { Year = 2020, Region = "Africa", Country = "Nigeria", Product = "Monitor", Sold = 156, Amount = 145860 },
            new SalesData { Year = 2020, Region = "Africa", Country = "Nigeria", Product = "Printer", Sold = 458, Amount = 275716 },
            new SalesData { Year = 2020, Region = "Africa", Country = "Egypt", Product = "Laptop", Sold = 386, Amount = 402212 },
            new SalesData { Year = 2020, Region = "Africa", Country = "Egypt", Product = "Smartphone", Sold = 461, Amount = 202379 },
            new SalesData { Year = 2020, Region = "Africa", Country = "Egypt", Product = "Tablet", Sold = 324, Amount = 60264 },
            new SalesData { Year = 2020, Region = "Africa", Country = "Egypt", Product = "Monitor", Sold = 344, Amount = 149984 },
            new SalesData { Year = 2020, Region = "Africa", Country = "Egypt", Product = "Printer", Sold = 455, Amount = 509145 },
            new SalesData { Year = 2020, Region = "Africa", Country = "South Africa", Product = "Laptop", Sold = 319, Amount = 86449 },
            new SalesData { Year = 2020, Region = "Africa", Country = "South Africa", Product = "Smartphone", Sold = -475, Amount = -280250 },
            new SalesData { Year = 2020, Region = "Africa", Country = "South Africa", Product = "Tablet", Sold = 199, Amount = 95918 },
            new SalesData { Year = 2020, Region = "Africa", Country = "South Africa", Product = "Monitor", Sold = 416, Amount = 320320 },
            new SalesData { Year = 2020, Region = "Africa", Country = "South Africa", Product = "Printer", Sold = 311, Amount = 174160 },
            new SalesData { Year = 2020, Region = "Australia", Country = "Australia", Product = "Laptop", Sold = 145, Amount = 122525 },
            new SalesData { Year = 2020, Region = "Australia", Country = "Australia", Product = "Smartphone", Sold = 204, Amount = 107304 },
            new SalesData { Year = 2020, Region = "Australia", Country = "Australia", Product = "Tablet", Sold = -203, Amount = -130123 },
            new SalesData { Year = 2020, Region = "Australia", Country = "Australia", Product = "Monitor", Sold = 496, Amount = 444416 },
            new SalesData { Year = 2020, Region = "Australia", Country = "Australia", Product = "Printer", Sold = 322, Amount = 170338 },
            new SalesData { Year = 2020, Region = "Australia", Country = "New Zealand", Product = "Laptop", Sold = 383, Amount = 93835 },
            new SalesData { Year = 2020, Region = "Australia", Country = "New Zealand", Product = "Smartphone", Sold = 361, Amount = 344755 },
            new SalesData { Year = 2020, Region = "Australia", Country = "New Zealand", Product = "Tablet", Sold = -253, Amount = -284119 },
            new SalesData { Year = 2020, Region = "Australia", Country = "New Zealand", Product = "Monitor", Sold = 416, Amount = 197600 },
            new SalesData { Year = 2020, Region = "Australia", Country = "New Zealand", Product = "Printer", Sold = 301, Amount = 277522 },
            new SalesData { Year = 2021, Region = "North America", Country = "USA", Product = "Laptop", Sold = 270, Amount = 105570 },
            new SalesData { Year = 2021, Region = "North America", Country = "USA", Product = "Smartphone", Sold = 338, Amount = 262288 },
            new SalesData { Year = 2021, Region = "North America", Country = "USA", Product = "Tablet", Sold = 441, Amount = 473634 },
            new SalesData { Year = 2021, Region = "North America", Country = "USA", Product = "Monitor", Sold = 134, Amount = 72628 },
            new SalesData { Year = 2021, Region = "North America", Country = "USA", Product = "Printer", Sold = 185, Amount = 188330 },
            new SalesData { Year = 2021, Region = "North America", Country = "Canada", Product = "Laptop", Sold = 360, Amount = 314280 },
            new SalesData { Year = 2021, Region = "North America", Country = "Canada", Product = "Smartphone", Sold = 441, Amount = 242991 },
            new SalesData { Year = 2021, Region = "North America", Country = "Canada", Product = "Tablet", Sold = 454, Amount = 204754 },
            new SalesData { Year = 2021, Region = "North America", Country = "Canada", Product = "Monitor", Sold = -208, Amount = -243360 },
            new SalesData { Year = 2021, Region = "North America", Country = "Canada", Product = "Printer", Sold = 361, Amount = 174002 },
            new SalesData { Year = 2021, Region = "North America", Country = "Mexico", Product = "Laptop", Sold = 135, Amount = 131085 },
            new SalesData { Year = 2021, Region = "North America", Country = "Mexico", Product = "Smartphone", Sold = -248, Amount = -242544 },
            new SalesData { Year = 2021, Region = "North America", Country = "Mexico", Product = "Tablet", Sold = 115, Amount = 61295 },
            new SalesData { Year = 2021, Region = "North America", Country = "Mexico", Product = "Monitor", Sold = -215, Amount = -54180 },
            new SalesData { Year = 2021, Region = "North America", Country = "Mexico", Product = "Printer", Sold = -201, Amount = -171453 },
            new SalesData { Year = 2021, Region = "South America", Country = "Brazil", Product = "Laptop", Sold = 261, Amount = 167823 },
            new SalesData { Year = 2021, Region = "South America", Country = "Brazil", Product = "Smartphone", Sold = 499, Amount = 494010 },
            new SalesData { Year = 2021, Region = "South America", Country = "Brazil", Product = "Tablet", Sold = 476, Amount = 481712 },
            new SalesData { Year = 2021, Region = "South America", Country = "Brazil", Product = "Monitor", Sold = 133, Amount = 50939 },
            new SalesData { Year = 2021, Region = "South America", Country = "Brazil", Product = "Printer", Sold = -342, Amount = -344736 },
            new SalesData { Year = 2021, Region = "South America", Country = "Argentina", Product = "Laptop", Sold = -141, Amount = -116184 },
            new SalesData { Year = 2021, Region = "South America", Country = "Argentina", Product = "Smartphone", Sold = 493, Amount = 451095 },
            new SalesData { Year = 2021, Region = "South America", Country = "Argentina", Product = "Tablet", Sold = -149, Amount = -130524 },
            new SalesData { Year = 2021, Region = "South America", Country = "Argentina", Product = "Monitor", Sold = 496, Amount = 370512 },
            new SalesData { Year = 2021, Region = "South America", Country = "Argentina", Product = "Printer", Sold = 304, Amount = 153216 },
            new SalesData { Year = 2021, Region = "South America", Country = "Chile", Product = "Laptop", Sold = 438, Amount = 422670 },
            new SalesData { Year = 2021, Region = "South America", Country = "Chile", Product = "Smartphone", Sold = 478, Amount = 107550 },
            new SalesData { Year = 2021, Region = "South America", Country = "Chile", Product = "Tablet", Sold = -341, Amount = -300762 },
            new SalesData { Year = 2021, Region = "South America", Country = "Chile", Product = "Monitor", Sold = 425, Amount = 184450 },
            new SalesData { Year = 2021, Region = "South America", Country = "Chile", Product = "Printer", Sold = 325, Amount = 136825 },
            new SalesData { Year = 2021, Region = "Europe", Country = "Germany", Product = "Laptop", Sold = 246, Amount = 192864 },
            new SalesData { Year = 2021, Region = "Europe", Country = "Germany", Product = "Smartphone", Sold = 487, Amount = 235221 },
            new SalesData { Year = 2021, Region = "Europe", Country = "Germany", Product = "Tablet", Sold = 222, Amount = 169830 },
            new SalesData { Year = 2021, Region = "Europe", Country = "Germany", Product = "Monitor", Sold = -459, Amount = -335529 },
            new SalesData { Year = 2021, Region = "Europe", Country = "Germany", Product = "Printer", Sold = 322, Amount = 94024 },
            new SalesData { Year = 2021, Region = "Europe", Country = "France", Product = "Laptop", Sold = -248, Amount = -234608 },
            new SalesData { Year = 2021, Region = "Europe", Country = "France", Product = "Smartphone", Sold = -108, Amount = -16524 },
            new SalesData { Year = 2021, Region = "Europe", Country = "France", Product = "Tablet", Sold = -238, Amount = -153748 },
            new SalesData { Year = 2021, Region = "Europe", Country = "France", Product = "Monitor", Sold = 366, Amount = 202764 },
            new SalesData { Year = 2021, Region = "Europe", Country = "France", Product = "Printer", Sold = -365, Amount = -77380 },
            new SalesData { Year = 2021, Region = "Europe", Country = "UK", Product = "Laptop", Sold = 122, Amount = 37576 },
            new SalesData { Year = 2021, Region = "Europe", Country = "UK", Product = "Smartphone", Sold = 402, Amount = 102510 },
            new SalesData { Year = 2021, Region = "Europe", Country = "UK", Product = "Tablet", Sold = 109, Amount = 55808 },
            new SalesData { Year = 2021, Region = "Europe", Country = "UK", Product = "Monitor", Sold = 425, Amount = 371450 },
            new SalesData { Year = 2021, Region = "Europe", Country = "UK", Product = "Printer", Sold = 156, Amount = 162708 },
            new SalesData { Year = 2021, Region = "Asia", Country = "China", Product = "Laptop", Sold = 134, Amount = 105190 },
            new SalesData { Year = 2021, Region = "Asia", Country = "China", Product = "Smartphone", Sold = 382, Amount = 263580 },
            new SalesData { Year = 2021, Region = "Asia", Country = "China", Product = "Tablet", Sold = 500, Amount = 586000 },
            new SalesData { Year = 2021, Region = "Asia", Country = "China", Product = "Monitor", Sold = -478, Amount = -316436 },
            new SalesData { Year = 2021, Region = "Asia", Country = "China", Product = "Printer", Sold = -424, Amount = -487176 },
            new SalesData { Year = 2021, Region = "Asia", Country = "India", Product = "Laptop", Sold = 244, Amount = 83936 },
            new SalesData { Year = 2021, Region = "Asia", Country = "India", Product = "Smartphone", Sold = 413, Amount = 409696 },
            new SalesData { Year = 2021, Region = "Asia", Country = "India", Product = "Tablet", Sold = 141, Amount = 77973 },
            new SalesData { Year = 2021, Region = "Asia", Country = "India", Product = "Monitor", Sold = 409, Amount = 316975 },
            new SalesData { Year = 2021, Region = "Asia", Country = "India", Product = "Printer", Sold = 315, Amount = 192465 },
            new SalesData { Year = 2021, Region = "Asia", Country = "Japan", Product = "Laptop", Sold = 103, Amount = 113918 },
            new SalesData { Year = 2021, Region = "Asia", Country = "Japan", Product = "Smartphone", Sold = 264, Amount = 66000 },
            new SalesData { Year = 2021, Region = "Asia", Country = "Japan", Product = "Tablet", Sold = 305, Amount = 121085 },
            new SalesData { Year = 2021, Region = "Asia", Country = "Japan", Product = "Monitor", Sold = 175, Amount = 186200 },
            new SalesData { Year = 2021, Region = "Asia", Country = "Japan", Product = "Printer", Sold = -184, Amount = -117208 },
            new SalesData { Year = 2021, Region = "Africa", Country = "Nigeria", Product = "Laptop", Sold = 171, Amount = 126027 },
            new SalesData { Year = 2021, Region = "Africa", Country = "Nigeria", Product = "Smartphone", Sold = 183, Amount = 45750 },
            new SalesData { Year = 2021, Region = "Africa", Country = "Nigeria", Product = "Tablet", Sold = 120, Amount = 27840 },
            new SalesData { Year = 2021, Region = "Africa", Country = "Nigeria", Product = "Monitor", Sold = 123, Amount = 59040 },
            new SalesData { Year = 2021, Region = "Africa", Country = "Nigeria", Product = "Printer", Sold = 498, Amount = 480570 },
            new SalesData { Year = 2021, Region = "Africa", Country = "Egypt", Product = "Laptop", Sold = -139, Amount = -61438 },
            new SalesData { Year = 2021, Region = "Africa", Country = "Egypt", Product = "Smartphone", Sold = 157, Amount = 43332 },
            new SalesData { Year = 2021, Region = "Africa", Country = "Egypt", Product = "Tablet", Sold = 237, Amount = 143622 },
            new SalesData { Year = 2021, Region = "Africa", Country = "Egypt", Product = "Monitor", Sold = -262, Amount = -120258 },
            new SalesData { Year = 2021, Region = "Africa", Country = "Egypt", Product = "Printer", Sold = -483, Amount = -180642 },
            new SalesData { Year = 2021, Region = "Africa", Country = "South Africa", Product = "Laptop", Sold = 222, Amount = 257520 },
            new SalesData { Year = 2021, Region = "Africa", Country = "South Africa", Product = "Smartphone", Sold = 446, Amount = 401846 },
            new SalesData { Year = 2021, Region = "Africa", Country = "South Africa", Product = "Tablet", Sold = 297, Amount = 55242 },
            new SalesData { Year = 2021, Region = "Africa", Country = "South Africa", Product = "Monitor", Sold = 474, Amount = 76314 },
            new SalesData { Year = 2021, Region = "Africa", Country = "South Africa", Product = "Printer", Sold = 467, Amount = 447853 },
            new SalesData { Year = 2021, Region = "Australia", Country = "Australia", Product = "Laptop", Sold = -279, Amount = -205344 },
            new SalesData { Year = 2021, Region = "Australia", Country = "Australia", Product = "Smartphone", Sold = 488, Amount = 404064 },
            new SalesData { Year = 2021, Region = "Australia", Country = "Australia", Product = "Tablet", Sold = 438, Amount = 477858 },
            new SalesData { Year = 2021, Region = "Australia", Country = "Australia", Product = "Monitor", Sold = -199, Amount = -62486 },
            new SalesData { Year = 2021, Region = "Australia", Country = "Australia", Product = "Printer", Sold = 113, Amount = 27007 },
            new SalesData { Year = 2021, Region = "Australia", Country = "New Zealand", Product = "Laptop", Sold = 486, Amount = 169128 },
            new SalesData { Year = 2021, Region = "Australia", Country = "New Zealand", Product = "Smartphone", Sold = 135, Amount = 87885 },
            new SalesData { Year = 2021, Region = "Australia", Country = "New Zealand", Product = "Tablet", Sold = 241, Amount = 178099 },
            new SalesData { Year = 2021, Region = "Australia", Country = "New Zealand", Product = "Monitor", Sold = 369, Amount = 412542 },
            new SalesData { Year = 2021, Region = "Australia", Country = "New Zealand", Product = "Printer", Sold = 189, Amount = 59157 },
            new SalesData { Year = 2022, Region = "North America", Country = "USA", Product = "Laptop", Sold = -117, Amount = -63882 },
            new SalesData { Year = 2022, Region = "North America", Country = "USA", Product = "Smartphone", Sold = -183, Amount = -68991 },
            new SalesData { Year = 2022, Region = "North America", Country = "USA", Product = "Tablet", Sold = -239, Amount = -200521 },
            new SalesData { Year = 2022, Region = "North America", Country = "USA", Product = "Monitor", Sold = 477, Amount = 518022 },
            new SalesData { Year = 2022, Region = "North America", Country = "USA", Product = "Printer", Sold = 209, Amount = 142747 },
            new SalesData { Year = 2022, Region = "North America", Country = "Canada", Product = "Laptop", Sold = 357, Amount = 294168 },
            new SalesData { Year = 2022, Region = "North America", Country = "Canada", Product = "Smartphone", Sold = 175, Amount = 130725 },
            new SalesData { Year = 2022, Region = "North America", Country = "Canada", Product = "Tablet", Sold = 386, Amount = 235460 },
            new SalesData { Year = 2022, Region = "North America", Country = "Canada", Product = "Monitor", Sold = 346, Amount = 208292 },
            new SalesData { Year = 2022, Region = "North America", Country = "Canada", Product = "Printer", Sold = 280, Amount = 184240 },
            new SalesData { Year = 2022, Region = "North America", Country = "Mexico", Product = "Laptop", Sold = 346, Amount = 57782 },
            new SalesData { Year = 2022, Region = "North America", Country = "Mexico", Product = "Smartphone", Sold = 396, Amount = 207504 },
            new SalesData { Year = 2022, Region = "North America", Country = "Mexico", Product = "Tablet", Sold = 406, Amount = 199752 },
            new SalesData { Year = 2022, Region = "North America", Country = "Mexico", Product = "Monitor", Sold = 178, Amount = 99324 },
            new SalesData { Year = 2022, Region = "North America", Country = "Mexico", Product = "Printer", Sold = 444, Amount = 348540 },
            new SalesData { Year = 2022, Region = "South America", Country = "Brazil", Product = "Laptop", Sold = 492, Amount = 577116 },
            new SalesData { Year = 2022, Region = "South America", Country = "Brazil", Product = "Smartphone", Sold = 464, Amount = 554480 },
            new SalesData { Year = 2022, Region = "South America", Country = "Brazil", Product = "Tablet", Sold = -166, Amount = -102920 },
            new SalesData { Year = 2022, Region = "South America", Country = "Brazil", Product = "Monitor", Sold = -230, Amount = -196650 },
            new SalesData { Year = 2022, Region = "South America", Country = "Brazil", Product = "Printer", Sold = 126, Amount = 89838 },
            new SalesData { Year = 2022, Region = "South America", Country = "Argentina", Product = "Laptop", Sold = 452, Amount = 421264 },
            new SalesData { Year = 2022, Region = "South America", Country = "Argentina", Product = "Smartphone", Sold = 340, Amount = 72420 },
            new SalesData { Year = 2022, Region = "South America", Country = "Argentina", Product = "Tablet", Sold = 232, Amount = 106024 },
            new SalesData { Year = 2022, Region = "South America", Country = "Argentina", Product = "Monitor", Sold = 151, Amount = 63420 },
            new SalesData { Year = 2022, Region = "South America", Country = "Argentina", Product = "Printer", Sold = 141, Amount = 111249 },
            new SalesData { Year = 2022, Region = "South America", Country = "Chile", Product = "Laptop", Sold = -164, Amount = -118572 },
            new SalesData { Year = 2022, Region = "South America", Country = "Chile", Product = "Smartphone", Sold = -360, Amount = -155880 },
            new SalesData { Year = 2022, Region = "South America", Country = "Chile", Product = "Tablet", Sold = 393, Amount = 253485 },
            new SalesData { Year = 2022, Region = "South America", Country = "Chile", Product = "Monitor", Sold = 419, Amount = 416486 },
            new SalesData { Year = 2022, Region = "South America", Country = "Chile", Product = "Printer", Sold = -392, Amount = -89768 },
            new SalesData { Year = 2022, Region = "Europe", Country = "Germany", Product = "Laptop", Sold = 243, Amount = 184680 },
            new SalesData { Year = 2022, Region = "Europe", Country = "Germany", Product = "Smartphone", Sold = 264, Amount = 60192 },
            new SalesData { Year = 2022, Region = "Europe", Country = "Germany", Product = "Tablet", Sold = 405, Amount = 232065 },
            new SalesData { Year = 2022, Region = "Europe", Country = "Germany", Product = "Monitor", Sold = 347, Amount = 187033 },
            new SalesData { Year = 2022, Region = "Europe", Country = "Germany", Product = "Printer", Sold = 174, Amount = 160080 },
            new SalesData { Year = 2022, Region = "Europe", Country = "France", Product = "Laptop", Sold = 328, Amount = 176464 },
            new SalesData { Year = 2022, Region = "Europe", Country = "France", Product = "Smartphone", Sold = 263, Amount = 98625 },
            new SalesData { Year = 2022, Region = "Europe", Country = "France", Product = "Tablet", Sold = 164, Amount = 97908 },
            new SalesData { Year = 2022, Region = "Europe", Country = "France", Product = "Monitor", Sold = 228, Amount = 184908 },
            new SalesData { Year = 2022, Region = "Europe", Country = "France", Product = "Printer", Sold = 227, Amount = 150501 },
            new SalesData { Year = 2022, Region = "Europe", Country = "UK", Product = "Laptop", Sold = -193, Amount = -132012 },
            new SalesData { Year = 2022, Region = "Europe", Country = "UK", Product = "Smartphone", Sold = 446, Amount = 304618 },
            new SalesData { Year = 2022, Region = "Europe", Country = "UK", Product = "Tablet", Sold = 491, Amount = 533717 },
            new SalesData { Year = 2022, Region = "Europe", Country = "UK", Product = "Monitor", Sold = 285, Amount = 71535 },
            new SalesData { Year = 2022, Region = "Europe", Country = "UK", Product = "Printer", Sold = 437, Amount = 249527 },
            new SalesData { Year = 2022, Region = "Asia", Country = "China", Product = "Laptop", Sold = -475, Amount = -435100 },
            new SalesData { Year = 2022, Region = "Asia", Country = "China", Product = "Smartphone", Sold = 280, Amount = 316120 },
            new SalesData { Year = 2022, Region = "Asia", Country = "China", Product = "Tablet", Sold = -220, Amount = -187000 },
            new SalesData { Year = 2022, Region = "Asia", Country = "China", Product = "Monitor", Sold = 448, Amount = 448000 },
            new SalesData { Year = 2022, Region = "Asia", Country = "China", Product = "Printer", Sold = 221, Amount = 186524 },
            new SalesData { Year = 2022, Region = "Asia", Country = "India", Product = "Laptop", Sold = 475, Amount = 563825 },
            new SalesData { Year = 2022, Region = "Asia", Country = "India", Product = "Smartphone", Sold = 229, Amount = 103279 },
            new SalesData { Year = 2022, Region = "Asia", Country = "India", Product = "Tablet", Sold = 377, Amount = 405652 },
            new SalesData { Year = 2022, Region = "Asia", Country = "India", Product = "Monitor", Sold = -328, Amount = -241408 },
            new SalesData { Year = 2022, Region = "Asia", Country = "India", Product = "Printer", Sold = 229, Amount = 236328 },
            new SalesData { Year = 2022, Region = "Asia", Country = "Japan", Product = "Laptop", Sold = 147, Amount = 153027 },
            new SalesData { Year = 2022, Region = "Asia", Country = "Japan", Product = "Smartphone", Sold = -205, Amount = -108650 },
            new SalesData { Year = 2022, Region = "Asia", Country = "Japan", Product = "Tablet", Sold = 376, Amount = 450448 },
            new SalesData { Year = 2022, Region = "Asia", Country = "Japan", Product = "Monitor", Sold = 325, Amount = 328575 },
            new SalesData { Year = 2022, Region = "Asia", Country = "Japan", Product = "Printer", Sold = -368, Amount = -89056 },
            new SalesData { Year = 2022, Region = "Africa", Country = "Nigeria", Product = "Laptop", Sold = 289, Amount = 152014 },
            new SalesData { Year = 2022, Region = "Africa", Country = "Nigeria", Product = "Smartphone", Sold = 273, Amount = 164892 },
            new SalesData { Year = 2022, Region = "Africa", Country = "Nigeria", Product = "Tablet", Sold = -476, Amount = -73304 },
            new SalesData { Year = 2022, Region = "Africa", Country = "Nigeria", Product = "Monitor", Sold = 118, Amount = 48498 },
            new SalesData { Year = 2022, Region = "Africa", Country = "Nigeria", Product = "Printer", Sold = 228, Amount = 236892 },
            new SalesData { Year = 2022, Region = "Africa", Country = "Egypt", Product = "Laptop", Sold = 191, Amount = 178776 },
            new SalesData { Year = 2022, Region = "Africa", Country = "Egypt", Product = "Smartphone", Sold = 169, Amount = 184717 },
            new SalesData { Year = 2022, Region = "Africa", Country = "Egypt", Product = "Tablet", Sold = 119, Amount = 107338 },
            new SalesData { Year = 2022, Region = "Africa", Country = "Egypt", Product = "Monitor", Sold = 321, Amount = 177834 },
            new SalesData { Year = 2022, Region = "Africa", Country = "Egypt", Product = "Printer", Sold = 380, Amount = 297540 },
            new SalesData { Year = 2022, Region = "Africa", Country = "South Africa", Product = "Laptop", Sold = 429, Amount = 187044 },
            new SalesData { Year = 2022, Region = "Africa", Country = "South Africa", Product = "Smartphone", Sold = -499, Amount = -543411 },
            new SalesData { Year = 2022, Region = "Africa", Country = "South Africa", Product = "Tablet", Sold = -494, Amount = -257374 },
            new SalesData { Year = 2022, Region = "Africa", Country = "South Africa", Product = "Monitor", Sold = 446, Amount = 232812 },
            new SalesData { Year = 2022, Region = "Africa", Country = "South Africa", Product = "Printer", Sold = 355, Amount = 321275 },
            new SalesData { Year = 2022, Region = "Australia", Country = "Australia", Product = "Laptop", Sold = 191, Amount = 162923 },
            new SalesData { Year = 2022, Region = "Australia", Country = "Australia", Product = "Smartphone", Sold = 164, Amount = 154324 },
            new SalesData { Year = 2022, Region = "Australia", Country = "Australia", Product = "Tablet", Sold = 367, Amount = 377276 },
            new SalesData { Year = 2022, Region = "Australia", Country = "Australia", Product = "Monitor", Sold = 241, Amount = 118813 },
            new SalesData { Year = 2022, Region = "Australia", Country = "Australia", Product = "Printer", Sold = 378, Amount = 105840 },
            new SalesData { Year = 2022, Region = "Australia", Country = "New Zealand", Product = "Laptop", Sold = 441, Amount = 472752 },
            new SalesData { Year = 2022, Region = "Australia", Country = "New Zealand", Product = "Smartphone", Sold = -120, Amount = -119880 },
            new SalesData { Year = 2022, Region = "Australia", Country = "New Zealand", Product = "Tablet", Sold = 492, Amount = 325704 },
            new SalesData { Year = 2022, Region = "Australia", Country = "New Zealand", Product = "Monitor", Sold = 247, Amount = 214396 },
            new SalesData { Year = 2022, Region = "Australia", Country = "New Zealand", Product = "Printer", Sold = 449, Amount = 354710 },
            new SalesData { Year = 2023, Region = "North America", Country = "USA", Product = "Laptop", Sold = -292, Amount = -200312 },
            new SalesData { Year = 2023, Region = "North America", Country = "USA", Product = "Smartphone", Sold = 308, Amount = 187264 },
            new SalesData { Year = 2023, Region = "North America", Country = "USA", Product = "Tablet", Sold = 129, Amount = 52374 },
            new SalesData { Year = 2023, Region = "North America", Country = "USA", Product = "Monitor", Sold = 496, Amount = 524272 },
            new SalesData { Year = 2023, Region = "North America", Country = "USA", Product = "Printer", Sold = 432, Amount = 345168 },
            new SalesData { Year = 2023, Region = "North America", Country = "Canada", Product = "Laptop", Sold = 454, Amount = 192042 },
            new SalesData { Year = 2023, Region = "North America", Country = "Canada", Product = "Smartphone", Sold = -150, Amount = -109800 },
            new SalesData { Year = 2023, Region = "North America", Country = "Canada", Product = "Tablet", Sold = 378, Amount = 374220 },
            new SalesData { Year = 2023, Region = "North America", Country = "Canada", Product = "Monitor", Sold = 500, Amount = 503500 },
            new SalesData { Year = 2023, Region = "North America", Country = "Canada", Product = "Printer", Sold = 387, Amount = 151704 },
            new SalesData { Year = 2023, Region = "North America", Country = "Mexico", Product = "Laptop", Sold = 222, Amount = 39738 },
            new SalesData { Year = 2023, Region = "North America", Country = "Mexico", Product = "Smartphone", Sold = 479, Amount = 196869 },
            new SalesData { Year = 2023, Region = "North America", Country = "Mexico", Product = "Tablet", Sold = 367, Amount = 183500 },
            new SalesData { Year = 2023, Region = "North America", Country = "Mexico", Product = "Monitor", Sold = 383, Amount = 444280 },
            new SalesData { Year = 2023, Region = "North America", Country = "Mexico", Product = "Printer", Sold = 485, Amount = 178480 },
            new SalesData { Year = 2023, Region = "South America", Country = "Brazil", Product = "Laptop", Sold = 134, Amount = 22780 },
            new SalesData { Year = 2023, Region = "South America", Country = "Brazil", Product = "Smartphone", Sold = 328, Amount = 181056 },
            new SalesData { Year = 2023, Region = "South America", Country = "Brazil", Product = "Tablet", Sold = 197, Amount = 118003 },
            new SalesData { Year = 2023, Region = "South America", Country = "Brazil", Product = "Monitor", Sold = 338, Amount = 116948 },
            new SalesData { Year = 2023, Region = "South America", Country = "Brazil", Product = "Printer", Sold = 269, Amount = 124009 },
            new SalesData { Year = 2023, Region = "South America", Country = "Argentina", Product = "Laptop", Sold = 335, Amount = 138690 },
            new SalesData { Year = 2023, Region = "South America", Country = "Argentina", Product = "Smartphone", Sold = 308, Amount = 196196 },
            new SalesData { Year = 2023, Region = "South America", Country = "Argentina", Product = "Tablet", Sold = 237, Amount = 46452 },
            new SalesData { Year = 2023, Region = "South America", Country = "Argentina", Product = "Monitor", Sold = 398, Amount = 305664 },
            new SalesData { Year = 2023, Region = "South America", Country = "Argentina", Product = "Printer", Sold = 187, Amount = 206822 },
            new SalesData { Year = 2023, Region = "South America", Country = "Chile", Product = "Laptop", Sold = -443, Amount = -460277 },
            new SalesData { Year = 2023, Region = "South America", Country = "Chile", Product = "Smartphone", Sold = -367, Amount = -308280 },
            new SalesData { Year = 2023, Region = "South America", Country = "Chile", Product = "Tablet", Sold = 165, Amount = 29040 },
            new SalesData { Year = 2023, Region = "South America", Country = "Chile", Product = "Monitor", Sold = 396, Amount = 295020 },
            new SalesData { Year = 2023, Region = "South America", Country = "Chile", Product = "Printer", Sold = 389, Amount = 243514 },
            new SalesData { Year = 2023, Region = "Europe", Country = "Germany", Product = "Laptop", Sold = 140, Amount = 36820 },
            new SalesData { Year = 2023, Region = "Europe", Country = "Germany", Product = "Smartphone", Sold = 379, Amount = 144778 },
            new SalesData { Year = 2023, Region = "Europe", Country = "Germany", Product = "Tablet", Sold = 396, Amount = 186120 },
            new SalesData { Year = 2023, Region = "Europe", Country = "Germany", Product = "Monitor", Sold = 264, Amount = 251328 },
            new SalesData { Year = 2023, Region = "Europe", Country = "Germany", Product = "Printer", Sold = 184, Amount = 191728 },
            new SalesData { Year = 2023, Region = "Europe", Country = "France", Product = "Laptop", Sold = 137, Amount = 134123 },
            new SalesData { Year = 2023, Region = "Europe", Country = "France", Product = "Smartphone", Sold = -104, Amount = -16536 },
            new SalesData { Year = 2023, Region = "Europe", Country = "France", Product = "Tablet", Sold = 148, Amount = 111000 },
            new SalesData { Year = 2023, Region = "Europe", Country = "France", Product = "Monitor", Sold = 356, Amount = 203988 },
            new SalesData { Year = 2023, Region = "Europe", Country = "France", Product = "Printer", Sold = 195, Amount = 209625 },
            new SalesData { Year = 2023, Region = "Europe", Country = "UK", Product = "Laptop", Sold = 221, Amount = 120666 },
            new SalesData { Year = 2023, Region = "Europe", Country = "UK", Product = "Smartphone", Sold = 426, Amount = 221094 },
            new SalesData { Year = 2023, Region = "Europe", Country = "UK", Product = "Tablet", Sold = -329, Amount = -282282 },
            new SalesData { Year = 2023, Region = "Europe", Country = "UK", Product = "Monitor", Sold = -250, Amount = -221000 },
            new SalesData { Year = 2023, Region = "Europe", Country = "UK", Product = "Printer", Sold = 182, Amount = 43498 },
            new SalesData { Year = 2023, Region = "Asia", Country = "China", Product = "Laptop", Sold = 317, Amount = 300199 },
            new SalesData { Year = 2023, Region = "Asia", Country = "China", Product = "Smartphone", Sold = 265, Amount = 87980 },
            new SalesData { Year = 2023, Region = "Asia", Country = "China", Product = "Tablet", Sold = -437, Amount = -493373 },
            new SalesData { Year = 2023, Region = "Asia", Country = "China", Product = "Monitor", Sold = 362, Amount = 261364 },
            new SalesData { Year = 2023, Region = "Asia", Country = "China", Product = "Printer", Sold = 162, Amount = 78408 },
            new SalesData { Year = 2023, Region = "Asia", Country = "India", Product = "Laptop", Sold = 382, Amount = 264344 },
            new SalesData { Year = 2023, Region = "Asia", Country = "India", Product = "Smartphone", Sold = 369, Amount = 85239 },
            new SalesData { Year = 2023, Region = "Asia", Country = "India", Product = "Tablet", Sold = 398, Amount = 429442 },
            new SalesData { Year = 2023, Region = "Asia", Country = "India", Product = "Monitor", Sold = 475, Amount = 107350 },
            new SalesData { Year = 2023, Region = "Asia", Country = "India", Product = "Printer", Sold = -247, Amount = -95095 },
            new SalesData { Year = 2023, Region = "Asia", Country = "Japan", Product = "Laptop", Sold = 282, Amount = 172866 },
            new SalesData { Year = 2023, Region = "Asia", Country = "Japan", Product = "Smartphone", Sold = 342, Amount = 259578 },
            new SalesData { Year = 2023, Region = "Asia", Country = "Japan", Product = "Tablet", Sold = 216, Amount = 191592 },
            new SalesData { Year = 2023, Region = "Asia", Country = "Japan", Product = "Monitor", Sold = 187, Amount = 98923 },
            new SalesData { Year = 2023, Region = "Asia", Country = "Japan", Product = "Printer", Sold = 187, Amount = 201960 },
            new SalesData { Year = 2023, Region = "Africa", Country = "Nigeria", Product = "Laptop", Sold = 352, Amount = 304832 },
            new SalesData { Year = 2023, Region = "Africa", Country = "Nigeria", Product = "Smartphone", Sold = -241, Amount = -210152 },
            new SalesData { Year = 2023, Region = "Africa", Country = "Nigeria", Product = "Tablet", Sold = 102, Amount = 93126 },
            new SalesData { Year = 2023, Region = "Africa", Country = "Nigeria", Product = "Monitor", Sold = 416, Amount = 81952 },
            new SalesData { Year = 2023, Region = "Africa", Country = "Nigeria", Product = "Printer", Sold = 491, Amount = 459576 },
            new SalesData { Year = 2023, Region = "Africa", Country = "Egypt", Product = "Laptop", Sold = 231, Amount = 270963 },
            new SalesData { Year = 2023, Region = "Africa", Country = "Egypt", Product = "Smartphone", Sold = 158, Amount = 170166 },
            new SalesData { Year = 2023, Region = "Africa", Country = "Egypt", Product = "Tablet", Sold = 365, Amount = 109135 },
            new SalesData { Year = 2023, Region = "Africa", Country = "Egypt", Product = "Monitor", Sold = 302, Amount = 264552 },
            new SalesData { Year = 2023, Region = "Africa", Country = "Egypt", Product = "Printer", Sold = 344, Amount = 336088 },
            new SalesData { Year = 2023, Region = "Africa", Country = "South Africa", Product = "Laptop", Sold = 135, Amount = 80595 },
            new SalesData { Year = 2023, Region = "Africa", Country = "South Africa", Product = "Smartphone", Sold = 406, Amount = 311402 },
            new SalesData { Year = 2023, Region = "Africa", Country = "South Africa", Product = "Tablet", Sold = 319, Amount = 253605 },
            new SalesData { Year = 2023, Region = "Africa", Country = "South Africa", Product = "Monitor", Sold = -439, Amount = -109750 },
            new SalesData { Year = 2023, Region = "Africa", Country = "South Africa", Product = "Printer", Sold = 236, Amount = 114460 },
            new SalesData { Year = 2023, Region = "Australia", Country = "Australia", Product = "Laptop", Sold = -447, Amount = -128736 },
            new SalesData { Year = 2023, Region = "Australia", Country = "Australia", Product = "Smartphone", Sold = 287, Amount = 55391 },
            new SalesData { Year = 2023, Region = "Australia", Country = "Australia", Product = "Tablet", Sold = 134, Amount = 36984 },
            new SalesData { Year = 2023, Region = "Australia", Country = "Australia", Product = "Monitor", Sold = 250, Amount = 39000 },
            new SalesData { Year = 2023, Region = "Australia", Country = "Australia", Product = "Printer", Sold = -284, Amount = -63048 },
            new SalesData { Year = 2023, Region = "Australia", Country = "New Zealand", Product = "Laptop", Sold = 449, Amount = 140088 },
            new SalesData { Year = 2023, Region = "Australia", Country = "New Zealand", Product = "Smartphone", Sold = 159, Amount = 109392 },
            new SalesData { Year = 2023, Region = "Australia", Country = "New Zealand", Product = "Tablet", Sold = 350, Amount = 246400 },
            new SalesData { Year = 2023, Region = "Australia", Country = "New Zealand", Product = "Monitor", Sold = 152, Amount = 120080 },
            new SalesData { Year = 2023, Region = "Australia", Country = "New Zealand", Product = "Printer", Sold = 143, Amount = 40183 },
            new SalesData { Year = 2024, Region = "North America", Country = "USA", Product = "Laptop", Sold = 196, Amount = 230692 },
            new SalesData { Year = 2024, Region = "North America", Country = "USA", Product = "Smartphone", Sold = 400, Amount = 339200 },
            new SalesData { Year = 2024, Region = "North America", Country = "USA", Product = "Tablet", Sold = -286, Amount = -310024 },
            new SalesData { Year = 2024, Region = "North America", Country = "USA", Product = "Monitor", Sold = 481, Amount = 176046 },
            new SalesData { Year = 2024, Region = "North America", Country = "USA", Product = "Printer", Sold = 201, Amount = 200598 },
            new SalesData { Year = 2024, Region = "North America", Country = "Canada", Product = "Laptop", Sold = 229, Amount = 97325 },
            new SalesData { Year = 2024, Region = "North America", Country = "Canada", Product = "Smartphone", Sold = 334, Amount = 191382 },
            new SalesData { Year = 2024, Region = "North America", Country = "Canada", Product = "Tablet", Sold = -234, Amount = -236574 },
            new SalesData { Year = 2024, Region = "North America", Country = "Canada", Product = "Monitor", Sold = 405, Amount = 345870 },
            new SalesData { Year = 2024, Region = "North America", Country = "Canada", Product = "Printer", Sold = 118, Amount = 106554 },
            new SalesData { Year = 2024, Region = "North America", Country = "Mexico", Product = "Laptop", Sold = 176, Amount = 166848 },
            new SalesData { Year = 2024, Region = "North America", Country = "Mexico", Product = "Smartphone", Sold = 464, Amount = 133632 },
            new SalesData { Year = 2024, Region = "North America", Country = "Mexico", Product = "Tablet", Sold = 417, Amount = 429510 },
            new SalesData { Year = 2024, Region = "North America", Country = "Mexico", Product = "Monitor", Sold = 202, Amount = 77164 },
            new SalesData { Year = 2024, Region = "North America", Country = "Mexico", Product = "Printer", Sold = 422, Amount = 254466 },
            new SalesData { Year = 2024, Region = "South America", Country = "Brazil", Product = "Laptop", Sold = 150, Amount = 112050 },
            new SalesData { Year = 2024, Region = "South America", Country = "Brazil", Product = "Smartphone", Sold = 168, Amount = 194208 },
            new SalesData { Year = 2024, Region = "South America", Country = "Brazil", Product = "Tablet", Sold = 215, Amount = 190275 },
            new SalesData { Year = 2024, Region = "South America", Country = "Brazil", Product = "Monitor", Sold = 175, Amount = 160125 },
            new SalesData { Year = 2024, Region = "South America", Country = "Brazil", Product = "Printer", Sold = 298, Amount = 275352 },
            new SalesData { Year = 2024, Region = "South America", Country = "Argentina", Product = "Laptop", Sold = 458, Amount = 527616 },
            new SalesData { Year = 2024, Region = "South America", Country = "Argentina", Product = "Smartphone", Sold = -333, Amount = -105894 },
            new SalesData { Year = 2024, Region = "South America", Country = "Argentina", Product = "Tablet", Sold = 208, Amount = 50336 },
            new SalesData { Year = 2024, Region = "South America", Country = "Argentina", Product = "Monitor", Sold = 180, Amount = 174060 },
            new SalesData { Year = 2024, Region = "South America", Country = "Argentina", Product = "Printer", Sold = 449, Amount = 404549 },
            new SalesData { Year = 2024, Region = "South America", Country = "Chile", Product = "Laptop", Sold = 200, Amount = 151600 },
            new SalesData { Year = 2024, Region = "South America", Country = "Chile", Product = "Smartphone", Sold = 294, Amount = 263718 },
            new SalesData { Year = 2024, Region = "South America", Country = "Chile", Product = "Tablet", Sold = 271, Amount = 143359 },
            new SalesData { Year = 2024, Region = "South America", Country = "Chile", Product = "Monitor", Sold = 267, Amount = 189036 },
            new SalesData { Year = 2024, Region = "South America", Country = "Chile", Product = "Printer", Sold = 122, Amount = 120536 },
            new SalesData { Year = 2024, Region = "Europe", Country = "Germany", Product = "Laptop", Sold = 149, Amount = 74947 },
            new SalesData { Year = 2024, Region = "Europe", Country = "Germany", Product = "Smartphone", Sold = 178, Amount = 198292 },
            new SalesData { Year = 2024, Region = "Europe", Country = "Germany", Product = "Tablet", Sold = 214, Amount = 151726 },
            new SalesData { Year = 2024, Region = "Europe", Country = "Germany", Product = "Monitor", Sold = 408, Amount = 214608 },
            new SalesData { Year = 2024, Region = "Europe", Country = "Germany", Product = "Printer", Sold = 150, Amount = 87900 },
            new SalesData { Year = 2024, Region = "Europe", Country = "France", Product = "Laptop", Sold = -354, Amount = -157176 },
            new SalesData { Year = 2024, Region = "Europe", Country = "France", Product = "Smartphone", Sold = 279, Amount = 173538 },
            new SalesData { Year = 2024, Region = "Europe", Country = "France", Product = "Tablet", Sold = 290, Amount = 149060 },
            new SalesData { Year = 2024, Region = "Europe", Country = "France", Product = "Monitor", Sold = 311, Amount = 125955 },
            new SalesData { Year = 2024, Region = "Europe", Country = "France", Product = "Printer", Sold = 428, Amount = 370648 },
            new SalesData { Year = 2024, Region = "Europe", Country = "UK", Product = "Laptop", Sold = 261, Amount = 304065 },
            new SalesData { Year = 2024, Region = "Europe", Country = "UK", Product = "Smartphone", Sold = 460, Amount = 120060 },
            new SalesData { Year = 2024, Region = "Europe", Country = "UK", Product = "Tablet", Sold = 194, Amount = 114848 },
            new SalesData { Year = 2024, Region = "Europe", Country = "UK", Product = "Monitor", Sold = -132, Amount = -62964 },
            new SalesData { Year = 2024, Region = "Europe", Country = "UK", Product = "Printer", Sold = 203, Amount = 40194 },
            new SalesData { Year = 2024, Region = "Asia", Country = "China", Product = "Laptop", Sold = -153, Amount = -136476 },
            new SalesData { Year = 2024, Region = "Asia", Country = "China", Product = "Smartphone", Sold = -405, Amount = -113805 },
            new SalesData { Year = 2024, Region = "Asia", Country = "China", Product = "Tablet", Sold = 407, Amount = 198616 },
            new SalesData { Year = 2024, Region = "Asia", Country = "China", Product = "Monitor", Sold = 175, Amount = 70350 },
            new SalesData { Year = 2024, Region = "Asia", Country = "China", Product = "Printer", Sold = 132, Amount = 36960 },
            new SalesData { Year = 2024, Region = "Asia", Country = "India", Product = "Laptop", Sold = -160, Amount = -134880 },
            new SalesData { Year = 2024, Region = "Asia", Country = "India", Product = "Smartphone", Sold = 362, Amount = 195842 },
            new SalesData { Year = 2024, Region = "Asia", Country = "India", Product = "Tablet", Sold = 482, Amount = 74228 },
            new SalesData { Year = 2024, Region = "Asia", Country = "India", Product = "Monitor", Sold = 449, Amount = 432836 },
            new SalesData { Year = 2024, Region = "Asia", Country = "India", Product = "Printer", Sold = 311, Amount = 303847 },
            new SalesData { Year = 2024, Region = "Asia", Country = "Japan", Product = "Laptop", Sold = 361, Amount = 193496 },
            new SalesData { Year = 2024, Region = "Asia", Country = "Japan", Product = "Smartphone", Sold = 381, Amount = 156210 },
            new SalesData { Year = 2024, Region = "Asia", Country = "Japan", Product = "Tablet", Sold = 373, Amount = 279004 },
            new SalesData { Year = 2024, Region = "Asia", Country = "Japan", Product = "Monitor", Sold = 451, Amount = 211519 },
            new SalesData { Year = 2024, Region = "Asia", Country = "Japan", Product = "Printer", Sold = 201, Amount = 52863 },
            new SalesData { Year = 2024, Region = "Africa", Country = "Nigeria", Product = "Laptop", Sold = 286, Amount = 222222 },
            new SalesData { Year = 2024, Region = "Africa", Country = "Nigeria", Product = "Smartphone", Sold = 424, Amount = 463432 },
            new SalesData { Year = 2024, Region = "Africa", Country = "Nigeria", Product = "Tablet", Sold = 383, Amount = 127156 },
            new SalesData { Year = 2024, Region = "Africa", Country = "Nigeria", Product = "Monitor", Sold = 306, Amount = 242046 },
            new SalesData { Year = 2024, Region = "Africa", Country = "Nigeria", Product = "Printer", Sold = 483, Amount = 478653 },
            new SalesData { Year = 2024, Region = "Africa", Country = "Egypt", Product = "Laptop", Sold = 230, Amount = 208610 },
            new SalesData { Year = 2024, Region = "Africa", Country = "Egypt", Product = "Smartphone", Sold = -123, Amount = -141942 },
            new SalesData { Year = 2024, Region = "Africa", Country = "Egypt", Product = "Tablet", Sold = -342, Amount = -337212 },
            new SalesData { Year = 2024, Region = "Africa", Country = "Egypt", Product = "Monitor", Sold = 300, Amount = 335400 },
            new SalesData { Year = 2024, Region = "Africa", Country = "Egypt", Product = "Printer", Sold = 471, Amount = 510093 },
            new SalesData { Year = 2024, Region = "Africa", Country = "South Africa", Product = "Laptop", Sold = 189, Amount = 90531 },
            new SalesData { Year = 2024, Region = "Africa", Country = "South Africa", Product = "Smartphone", Sold = 456, Amount = 108072 },
            new SalesData { Year = 2024, Region = "Africa", Country = "South Africa", Product = "Tablet", Sold = 197, Amount = 211184 },
            new SalesData { Year = 2024, Region = "Africa", Country = "South Africa", Product = "Monitor", Sold = 278, Amount = 299406 },
            new SalesData { Year = 2024, Region = "Africa", Country = "South Africa", Product = "Printer", Sold = 362, Amount = 55386 },
            new SalesData { Year = 2024, Region = "Australia", Country = "Australia", Product = "Laptop", Sold = 369, Amount = 324351 },
            new SalesData { Year = 2024, Region = "Australia", Country = "Australia", Product = "Smartphone", Sold = -139, Amount = -63662 },
            new SalesData { Year = 2024, Region = "Australia", Country = "Australia", Product = "Tablet", Sold = 358, Amount = 384850 },
            new SalesData { Year = 2024, Region = "Australia", Country = "Australia", Product = "Monitor", Sold = 286, Amount = 253110 },
            new SalesData { Year = 2024, Region = "Australia", Country = "Australia", Product = "Printer", Sold = 439, Amount = 234865 },
            new SalesData { Year = 2024, Region = "Australia", Country = "New Zealand", Product = "Laptop", Sold = 349, Amount = 189856 },
            new SalesData { Year = 2024, Region = "Australia", Country = "New Zealand", Product = "Smartphone", Sold = 237, Amount = 130824 },
            new SalesData { Year = 2024, Region = "Australia", Country = "New Zealand", Product = "Tablet", Sold = -332, Amount = -226756 },
            new SalesData { Year = 2024, Region = "Australia", Country = "New Zealand", Product = "Monitor", Sold = 388, Amount = 462108 },
            new SalesData { Year = 2024, Region = "Australia", Country = "New Zealand", Product = "Printer", Sold = 383, Amount = 336274 },
        };
    }
}